### ISSUE TITLE
Make FD# configurable

### ISSUE THREAD

**Issue by mikehale** [zimbatm/socketmaster#11]
Some processes like ruby assume low numbered (1-7 I think) file descriptors are reserved for internal vm use and block access to fd3. Instead of hardcoding the fd# allow it to be configured.

**Comment by zimbatm** [comment]
I don't think that it's true if the file descriptor already holds the position. I was running ruby processes with fd3 just fine at least. ?

**Comment by jingweno** [comment]
Maybe I do not understand Unix enough. Why is fd3 so special?

**Comment by jingweno** [comment]
Is it because the inherited socket file of socketmaster is the 3rd one [here](https://github.com/zimbatm/socketmaster/blob/master/process_group.go#L49)?

**Comment by zimbatm** [comment]
It's not really special. FDs are allocated linearly so 3 is just the next FD after stdin (0), stdout (1) and stderr (2). Otherwise it's possible to select an arbitrary FD number using the `dup2` syscall but I don't know if go provides that level of control for new processes.

You're welcome to try and submit a PR.

**Comment by mikehale** [comment]
> I don't think that it's true if the file descriptor already holds the position. I was running ruby processes with fd3 just fine at least. ?

Yeah, I see that the childserver.rb example works fine. I'm not sure exactly what I was trying before, but it seems like ruby and socketmaster work just fine with fd3.

Thanks, and sorry for the noise.

**Comment by zimbatm** [comment]
No worries, learning is good !
